### ISSUE TITLE
一个为next开发的浏览器

### ISSUE THREAD

**Issue by Weijia-Tong** [Zitann/HarmonyOS-Haps#1]
软件：冲浪喵
下载链接：https://github.com/awaLiny2333/LinysBrowser_NEXT/releases/download/v1.5.0-beta/HMOS-home-default-unsigned.hap
仓库：https://github.com/awaLiny2333/LinysBrowser_NEXT
作者：https://github.com/awaLiny2333
描述：Liny 的浏览器为 HarmonyOS NEXT 而构建，旨在为各种性能水平的设备提供一个浏览器的轻量之选。

我帮宣传一下（

**Comment by Zitann** [comment]
好的👌，晚上添加

**Comment by Zitann** [comment]
已添加👍
帮我的仓库一起宣传一下（😘
