### ISSUE TITLE
推荐一个未收录的鸿蒙Hap

### ISSUE THREAD

**Issue by 000wbh000** [Zitann/HarmonyOS-Haps#4]
Kazumi：一个基于自定义规则的番剧采集与在线观看程序。
链接：https://github.com/ErBWs/Kazumi/releases

**Comment by Zitann** [comment]
已收录，感谢推荐ヾ(≧▽≦*)o

**Comment by Zitann** [comment]
已收录，感谢推荐ヾ(≧▽≦*)o

**Comment by Zitann** [comment]
已收录，感谢推荐ヾ(≧▽≦*)o
